services:
  postgres:
    image: postgres:16-alpine
    container_name: foodrecipe_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: foodrecipe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Ho_Chi_Minh
      PGTZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - foodrecipe_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d foodrecipe_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  foodrecipe_pgdata:
    driver: local
